repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/pylint-dev/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args: [ "-rn", "-sn", "--rcfile=pylintrc", "--fail-on=I" ]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|test|pylintrc
